# Generated by Django 4.2.10 on 2024-03-11 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skinCare', '0006_itemdetails_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='CartItem',
        ),
    ]
