# Generated by Django 4.2.10 on 2024-03-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skinCare', '0008_rename_cartitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Id_product',
            field=models.IntegerField(null=True),
        ),
    ]
